# Builds HOLES.md: catalogs every reconstruction site in the decompiled
# GAME6.TXT. Each hole gets line number, surrounding context, and a
# best-guess at intent based on Kreuzer engine patterns.
param(
  [string]$DecompPath = "C:\Code\darkv-bas\Decompile\GAME6.TXT",
  [string]$OutPath = "C:\Code\darkv-bas\Decompile\Recon\HOLES.md"
)

$lines = Get-Content $DecompPath

function Get-Context {
  param([int]$Index, [int]$Before = 2, [int]$After = 2)
  $lo = [Math]::Max(0, $Index - $Before)
  $hi = [Math]::Min($lines.Count - 1, $Index + $After)
  $out = @()
  for ($i = $lo; $i -le $hi; $i++) {
    $marker = if ($i -eq $Index) { '>>' } else { '  ' }
    $out += ('{0} {1,5}: {2}' -f $marker, ($i + 1), $lines[$i])
  }
  return ($out -join "`n")
}

$holes = New-Object System.Collections.Generic.List[PSCustomObject]

for ($n = 0; $n -lt $lines.Count; $n++) {
  $line = $lines[$n]
  $kind = $null
  $detail = $null

  if ($line -match '^Rem error (\d+) \((.*?)\)') {
    $kind = "Rem error $($Matches[1])"
    $detail = "QB error $($Matches[1]) with args ($($Matches[2])) - Spring could not decode this instruction"
  }
  elseif ($line -match "'\?\?\?\?") {
    $kind = "???? target"
    $detail = "Unresolved GOTO/GOSUB target marker"
  }
  elseif ($line -match 'Subroutine S(\d+)') {
    $kind = "Subroutine pseudo-label"
    $detail = "Spring artifact: marks where a SUB or label begins at line $($Matches[1])"
  }
  elseif ($line -match 'S\?\?\?\?') {
    $kind = "S???? target"
    $detail = "Unresolved GOSUB/GOTO target name"
  }

  if ($kind) {
    $context = Get-Context -Index $n
    $holes.Add([PSCustomObject]@{
      LineNumber = $n + 1
      Kind = $kind
      Detail = $detail
      Line = $line
      Context = $context
    }) | Out-Null
  }
}

$grouped = $holes | Group-Object Kind | Sort-Object Count -Descending

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# DV1 Decompile Holes Report')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by tools/build_holes_report.ps1. Catalogs every reconstruction site in Decompile/GAME6.TXT.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Summary')
[void]$sb.AppendLine()
[void]$sb.AppendLine("- Total decompile lines: **$($lines.Count)**")
[void]$sb.AppendLine("- Total holes: **$($holes.Count)**")
foreach ($g in $grouped) {
  [void]$sb.AppendLine("- ``$($g.Name)``: **$($g.Count)**")
}
[void]$sb.AppendLine()

[void]$sb.AppendLine('## What each kind means')
[void]$sb.AppendLine()
[void]$sb.AppendLine('### Subroutine pseudo-label')
[void]$sb.AppendLine('Spring artifact. Marks where a SUB or labeled block begins in the original.')
[void]$sb.AppendLine('Reconstruction: mechanical - convert `Subroutine SNNNN` to a label `SNNNN:`. Most are inline labels, not SUB blocks (matches DV2/Dream-Giver style).')
[void]$sb.AppendLine()
[void]$sb.AppendLine('### Rem error 12')
[void]$sb.AppendLine('QB error 12 = Illegal function call. Spring placeholder for an instruction it could not decode.')
[void]$sb.AppendLine('Reconstruction: pattern-match neighboring code. Likely a PUT/GET/PALETTE/SOUND call. Recover from Dream-Giver patterns + EXE empirical check via DOSBox debugger.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('### Rem error 17')
[void]$sb.AppendLine('QB error 17 = Subscript out of range. Spring placeholder for an array access it could not decode.')
[void]$sb.AppendLine('Reconstruction: reconstruct from surrounding loop context (the array and index are usually obvious from nearby code).')
[void]$sb.AppendLine()
[void]$sb.AppendLine('### ???? target / S???? target')
[void]$sb.AppendLine('Unresolved GOTO/GOSUB target. Spring could not match the branch destination to a known line.')
[void]$sb.AppendLine('Reconstruction: match to a known label by line-number proximity + control flow context.')
[void]$sb.AppendLine()

foreach ($g in $grouped) {
  [void]$sb.AppendLine("## $($g.Name) - $($g.Count) sites")
  [void]$sb.AppendLine()
  foreach ($h in $g.Group) {
    [void]$sb.AppendLine("### Line $($h.LineNumber): ``$($h.Line.Trim())``")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("**Detail**: $($h.Detail)")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine($h.Context)
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine()
  }
}

[System.IO.File]::WriteAllText($OutPath, $sb.ToString())
"Wrote $OutPath ($($holes.Count) holes total)"
$grouped | ForEach-Object { "  $($_.Name): $($_.Count)" }
