# Builds STRINGS.md: cross-reference of strings in GAME.EXE vs. literals already
# present in the decompiled GAME6.TXT. Identifies candidates for missing content.
param(
  [string]$ExePath = "C:\Code\darkv-bas\GAME.EXE",
  [string]$DecompPath = "C:\Code\darkv-bas\Decompile\GAME6.TXT",
  [string]$OutPath = "C:\Code\darkv-bas\Decompile\Recon\STRINGS.md"
)

$here = Split-Path -Parent $MyInvocation.MyCommand.Path

# 1. Strings in EXE
$exeStrings = & "$here\extract_strings.ps1" -Path $ExePath -MinLength 4

# 2. Symbol table
$syms = & "$here\parse_symbol_table.ps1" -Path $DecompPath

# 3. String literals in decompile (anything between double quotes, trimmed)
$decompText = Get-Content $DecompPath -Raw
$decompLiterals = New-Object System.Collections.Generic.List[string]
foreach ($m in ([regex]::Matches($decompText, '"([^"]*)"'))) {
  $v = $m.Groups[1].Value
  if ($v.Length -ge 3) { $decompLiterals.Add($v) | Out-Null }
}
$decompLiteralsTrimmed = New-Object System.Collections.Generic.HashSet[string]
foreach ($l in $decompLiterals) { [void]$decompLiteralsTrimmed.Add($l.Trim()) }

# Helper: looks-like-content heuristic. Drop strings dominated by non-alphanum chars.
function Is-LikelyContent {
  param([string]$Text)
  if ($Text.Length -lt 5) { return $false }
  $alphaCount = 0
  foreach ($c in $Text.ToCharArray()) {
    if (($c -ge 'A' -and $c -le 'Z') -or ($c -ge 'a' -and $c -le 'z') -or $c -eq ' ') { $alphaCount++ }
  }
  $ratio = $alphaCount / $Text.Length
  # Require at least 60% letters/spaces; also require at least one lowercase word-ish run
  if ($ratio -lt 0.6) { return $false }
  if ($Text -notmatch '[a-z]{3,}') { return $false }
  return $true
}

# Helper: bidirectional contains (either string contains the other, with trimming)
function Strings-Overlap {
  param([string]$A, [string]$B)
  $a2 = $A.Trim()
  $b2 = $B.Trim()
  if ($a2.Length -lt 4 -or $b2.Length -lt 4) { return $false }
  return ($a2 -eq $b2) -or ($a2.Contains($b2)) -or ($b2.Contains($a2))
}

# 4. Detect QB45 runtime error message block by scanning for known sentinels.
$runtimeStart = ($exeStrings | Where-Object { $_.Text -eq 'Syntax error' } | Select-Object -First 1).Offset
$runtimeEnd = 0
if ($runtimeStart) {
  $sentinels = @('Syntax error','RETURN without GOSUB','Out of memory','Type mismatch',
                 'Out of string space','Device timeout','CASE ELSE expected','Internal error',
                 'Bad file name or number','File not found','Bad file mode','File already open',
                 'Device I/O error','File already exists','Bad record length','Input past end of file',
                 'Bad record number','Bad file name','Disk full','Permission denied','Disk not Ready',
                 'Disk media error','Path/File access error','Path not found','Variable required',
                 'Packed file is corrupt','Advanced feature unavailable','Rename across disks',
                 'Communication-buffer overflow','RND - Number out of range','Function not defined',
                 'Out of stack space','Cannot continue','Communication queue full',
                 '- control-BREAK encountered','- floating point not loaded','- illegal far pointer use',
                 '- illegal near pointer use','- integer divide by 0','- not enough space for arguments',
                 '- not enough space for environment','- stack overflow','- unexpected interrupt')
  $sentSet = New-Object System.Collections.Generic.HashSet[string]
  foreach ($s in $sentinels) { [void]$sentSet.Add($s) }
  $maxEnd = $runtimeStart
  foreach ($s in $exeStrings) {
    if ($s.Offset -lt $runtimeStart) { continue }
    if ($sentSet.Contains($s.Text)) { $maxEnd = [Math]::Max($maxEnd, $s.Offset + $s.Length) }
  }
  $runtimeEnd = $maxEnd + 200  # small pad past the last known sentinel
}

# 5. Classify
$classified = foreach ($s in $exeStrings) {
  $cat = $null
  if ($s.Length -lt 5) { $cat = 'noise-short' }
  elseif ($s.Offset -lt 1024) { $cat = 'exe-header' }
  elseif ($runtimeStart -and $s.Offset -ge $runtimeStart -and $s.Offset -lt $runtimeEnd) { $cat = 'qb-runtime' }
  elseif (-not (Is-LikelyContent $s.Text)) { $cat = 'noise-binary' }
  else {
    $matched = $false
    foreach ($lit in $decompLiterals) {
      if (Strings-Overlap $s.Text $lit) { $matched = $true; break }
    }
    if ($matched) { $cat = 'in-decompile' } else { $cat = 'MISSING-FROM-DECOMPILE' }
  }
  [PSCustomObject]@{
    Offset = $s.Offset
    OffsetHex = ('0x{0:X4}' -f $s.Offset)
    Length = $s.Length
    Text = $s.Text
    Category = $cat
  }
}

# 6. Build report
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# DV1 Strings Analysis')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by `tools/build_strings_report.ps1`. Cross-references printable')
[void]$sb.AppendLine('strings in `GAME.EXE` against literals already present in `GAME6.TXT`.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Summary')
[void]$sb.AppendLine()
[void]$sb.AppendLine("- EXE strings (len >= 4): **$($exeStrings.Count)**")
[void]$sb.AppendLine("- Decompile string literals: **$($decompLiterals.Count)**")
$catCounts = $classified | Group-Object Category | Sort-Object Count -Descending
foreach ($g in $catCounts) {
  [void]$sb.AppendLine("- ``$($g.Name)``: **$($g.Count)**")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## String variables in COMMON SHARED')
[void]$sb.AppendLine()
[void]$sb.AppendLine('From `GAME6.TXT` symbol table. Arrays (`SA`) are the content tables we expect to hold the missing room/object/dialogue strings. Scalars (`S`) are runtime working variables.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Variable | Address | Flags | Role guess |')
[void]$sb.AppendLine('|----------|---------|-------|------------|')
$roleGuesses = @{
  'L22$' = 'INKEY$ buffer (a$ in Dream-Giver/DV2)'
  'L36$' = 'Current scene/room name (q$ in Dream-Giver/DV2)'
  'L142$' = 'Current message (mess$ in DV2)'
  'L274$' = 'Previous message / last$ (DV2)'
  'L275$' = 'Previous message / less$ (DV2)'
  'L325$' = 'Working string'
  'L348$' = 'Working string'
  'L357$' = 'Working string'
  'L406$' = 'Working string'
  'L448$' = 'Working string'
  'L482$' = 'Working string'
  'I107$' = 'Working string (Spring quirk: I prefix + $ suffix)'
  'L339$' = 'String ARRAY: per Dream-Giver mess$(40)'
  'L322$' = 'String ARRAY: room/object names'
  'L315$' = 'String ARRAY: room/object names'
  'L323$' = 'String ARRAY: action dispatch (df$)'
  'L476$' = 'String ARRAY: per-row hit-grid strings (vh$ in DV2/DG)'
}
foreach ($s in ($syms | Where-Object { $_.Type -eq 'String' } | Sort-Object Address)) {
  $role = $roleGuesses[$s.Name]
  if (-not $role) { $role = '?' }
  $arr = if ($s.IsArray) { '(array)' } else { '(scalar)' }
  [void]$sb.AppendLine("| ``$($s.Name)`` $arr | 0x$($s.AddressHex) | $($s.Flags) | $role |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Strings present in EXE but NOT in decompile (game content candidates)')
[void]$sb.AppendLine()
[void]$sb.AppendLine('These are the strongest candidates for recovered content — strings that pass a "looks like English text" heuristic and have no overlap with any `"..."` literal in the decompile.')
[void]$sb.AppendLine()
$missing = $classified | Where-Object { $_.Category -eq 'MISSING-FROM-DECOMPILE' } | Sort-Object Offset
[void]$sb.AppendLine("Count: **$($missing.Count)**")
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Offset | Len | Text |')
[void]$sb.AppendLine('|--------|-----|------|')
foreach ($s in $missing) {
  $clean = $s.Text -replace '\|', '\|'
  [void]$sb.AppendLine("| $($s.OffsetHex) | $($s.Length) | ``$clean`` |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Strings appearing in BOTH (sanity check)')
[void]$sb.AppendLine()
$both = $classified | Where-Object { $_.Category -eq 'in-decompile' } | Sort-Object Offset
[void]$sb.AppendLine("Count: **$($both.Count)** _(showing first 50)_")
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Offset | Len | Text |')
[void]$sb.AppendLine('|--------|-----|------|')
foreach ($s in ($both | Select-Object -First 50)) {
  $clean = $s.Text -replace '\|', '\|'
  [void]$sb.AppendLine("| $($s.OffsetHex) | $($s.Length) | ``$clean`` |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Filter notes')
[void]$sb.AppendLine()
[void]$sb.AppendLine('- `noise-short` (len < 5) and `noise-binary` (low alpha ratio or no 3+ letter run) are filtered out.')
[void]$sb.AppendLine("- `qb-runtime`: QB45 runtime error-message block, range 0x$('{0:X}' -f $runtimeStart)..0x$('{0:X}' -f $runtimeEnd).")
[void]$sb.AppendLine('- Strings starting with a leading digit (e.g. `8sub1`) are direction-prefixed room names — see Dream-Giver `da$()` pattern.')

[System.IO.File]::WriteAllText($OutPath, $sb.ToString())
"Wrote $OutPath ($($classified.Count) classified, $($missing.Count) missing, $($both.Count) in-decompile)"
