# Finds where missing RETURN statements should be inserted in GAME.BAS.
#
# Spring's decompiler lost ALL RETURNs (0 in original, 104 GOSUB calls).
# This tool finds each GOSUB target and identifies where the subroutine
# probably ends, suggesting RETURN insertion points.
#
# Heuristic: a GOSUB target's routine ends at the first "exit boundary":
#   - The next labeled line that is itself a GOSUB target (start of next sub)
#   - An unconditional GoTo out of the local range
#   - A System / End statement
#   - The closest preceding line before a much-higher GOSUB target
param(
  [string]$BasPath = "C:\Code\darkv-bas\Decompile\Recon\GAME.BAS",
  [string]$OutPath = "C:\Code\darkv-bas\Decompile\Recon\MISSING_RETURNS.md"
)

$lines = Get-Content $BasPath

# 1) Find all GOSUB targets
$gosubTargets = New-Object System.Collections.Generic.HashSet[int]
$gosubCalls = @{}  # target -> list of caller line file-positions
for ($i = 0; $i -lt $lines.Count; $i++) {
  $line = $lines[$i]
  if ($line -match "^'") { continue }
  foreach ($m in [regex]::Matches($line, '\b(?:GoSub|GOSUB)\s+(\d+)\b')) {
    $tgt = [int]$m.Groups[1].Value
    [void]$gosubTargets.Add($tgt)
    if (-not $gosubCalls.ContainsKey($tgt)) { $gosubCalls[$tgt] = @() }
    $gosubCalls[$tgt] += $i + 1
  }
}

# 2) Build a map: QB line number -> file line index (so we can find target locations)
$qbToFile = @{}
for ($i = 0; $i -lt $lines.Count; $i++) {
  if ($lines[$i] -match '^(\d+)\b') {
    $qbToFile[[int]$Matches[1]] = $i
  }
}

# 3) For each unique GOSUB target, walk forward to find natural exit point
$sortedTargets = $gosubTargets | Sort-Object
$suggestions = New-Object System.Collections.Generic.List[PSCustomObject]

foreach ($target in $sortedTargets) {
  if (-not $qbToFile.ContainsKey($target)) { continue }
  $startIdx = $qbToFile[$target]
  $callers = ($gosubCalls[$target] -join ',')

  # Find the next GOSUB target after this one (acts as boundary)
  $nextTarget = $sortedTargets | Where-Object { $_ -gt $target } | Select-Object -First 1
  $nextTargetIdx = if ($nextTarget) { $qbToFile[$nextTarget] } else { $lines.Count }

  # Walk from startIdx forward; find first natural "exit" boundary
  $exitIdx = -1
  $exitReason = ''
  for ($i = $startIdx + 1; $i -lt $nextTargetIdx; $i++) {
    $l = $lines[$i]
    if ($l -match '^\s*\d+\s+System\b') { $exitIdx = $i; $exitReason = 'System'; break }
    if ($l -match '^\s*\d+\s+End\s*$') { $exitIdx = $i; $exitReason = 'End'; break }
    if ($l -match '^\s*\d+\s+End\s+Sub\b') { $exitIdx = $i; $exitReason = 'End Sub'; break }
    if ($l -match '^\s*\d+\s+RETURN\b' -or $l -match '^\s*\d+\s+Return\b') { $exitIdx = $i; $exitReason = 'existing RETURN'; break }
  }

  $existingReturn = ($exitReason -eq 'existing RETURN')
  $hasReturn = $false
  if (-not $existingReturn) {
    # Check if there's a RETURN anywhere between target and nextTarget
    for ($i = $startIdx; $i -lt $nextTargetIdx; $i++) {
      if ($lines[$i] -match '\bRETURN\b' -or $lines[$i] -match '\bReturn\b') { $hasReturn = $true; break }
    }
  }

  $suggestion = ''
  if ($existingReturn -or $hasReturn) {
    $suggestion = 'OK (has RETURN)'
  } elseif ($exitReason -ne '') {
    $suggestion = "Insert RETURN before $exitReason at file line $($exitIdx + 1)"
  } else {
    # No exit found - the next-target boundary is the end of this sub
    $beforeNextLine = $lines[$nextTargetIdx - 1]
    $suggestion = "Insert RETURN at file line $nextTargetIdx (before next GOSUB target). Last line: ``$($beforeNextLine.Trim())``"
  }

  $suggestions.Add([PSCustomObject]@{
    QBLine = $target
    FileLine = $startIdx + 1
    Callers = $callers
    NextTarget = $nextTarget
    Suggestion = $suggestion
    HasReturn = ($existingReturn -or $hasReturn)
  }) | Out-Null
}

$missingCount = ($suggestions | Where-Object { -not $_.HasReturn }).Count
$okCount = ($suggestions | Where-Object { $_.HasReturn }).Count

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Missing RETURN Statement Analysis')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by tools/find_missing_returns.ps1.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Spring lost ALL RETURN statements from the decompile (0 in GAME6.TXT).')
[void]$sb.AppendLine('This report lists every unique GOSUB target and suggests where its RETURN belongs.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Summary')
[void]$sb.AppendLine()
[void]$sb.AppendLine("- Unique GOSUB targets: **$($sortedTargets.Count)**")
[void]$sb.AppendLine("- Already have RETURN (manually added): **$okCount**")
[void]$sb.AppendLine("- Missing RETURN (need fix): **$missingCount**")
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Targets missing RETURN')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| QB line | File line | Called from | Suggestion |')
[void]$sb.AppendLine('|---------|-----------|-------------|------------|')
foreach ($s in ($suggestions | Where-Object { -not $_.HasReturn } | Sort-Object QBLine)) {
  [void]$sb.AppendLine("| $($s.QBLine) | $($s.FileLine) | $($s.Callers) | $($s.Suggestion) |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Targets with RETURN already present')
[void]$sb.AppendLine()
foreach ($s in ($suggestions | Where-Object { $_.HasReturn } | Sort-Object QBLine)) {
  [void]$sb.AppendLine("- QB line $($s.QBLine) (called from $($s.Callers))")
}

[System.IO.File]::WriteAllText($OutPath, $sb.ToString())
"Wrote $OutPath"
"  Unique GOSUB targets: $($sortedTargets.Count)"
"  Already have RETURN: $okCount"
"  Missing RETURN: $missingCount"
