# Inspects DV1 resource files in /org/ and reports the structure of each format.
# Output: prints a per-format table to stdout and optionally writes a summary.
param(
  [string]$OrgPath = "C:\Code\darkv-bas\org",
  [string]$OutPath = "C:\Code\darkv-bas\Decompile\Recon\RESOURCES.md"
)

function Inspect-Pac {
  param([string]$Path)
  $lines = Get-Content $Path
  $header = $lines[0]
  $entries = 0
  $zeros = 0
  $allValid = $true
  for ($i = 1; $i -lt $lines.Count; $i++) {
    $l = $lines[$i].Trim()
    if ($l -eq '') { continue }
    $parts = $l.Split(',')
    if ($parts.Count -ne 3) { $allValid = $false; continue }
    if ($parts[0].Trim() -eq '0' -and $parts[1].Trim() -eq '0' -and $parts[2].Trim() -eq '0') {
      $zeros++
    } else {
      $entries++
    }
  }
  [PSCustomObject]@{
    Name = (Split-Path $Path -Leaf)
    Bytes = (Get-Item $Path).Length
    Header = $header
    Entries = $entries
    ZeroPadding = $zeros
    LinesValid = $allValid
  }
}

function Inspect-Pct {
  param([string]$Path)
  $lines = Get-Content $Path
  $rows = 0
  $bad = 0
  $minVal = [int]::MaxValue
  $maxVal = [int]::MinValue
  foreach ($l in $lines) {
    $l = $l.Trim()
    if ($l -eq '') { continue }
    $parts = $l.Split(',')
    if ($parts.Count -eq 4) {
      $rows++
      foreach ($p in $parts) {
        $v = 0
        if ([int]::TryParse($p.Trim(), [ref]$v)) {
          if ($v -lt $minVal) { $minVal = $v }
          if ($v -gt $maxVal) { $maxVal = $v }
        }
      }
    } else { $bad++ }
  }
  [PSCustomObject]@{
    Name = (Split-Path $Path -Leaf)
    Bytes = (Get-Item $Path).Length
    Rows = $rows
    Malformed = $bad
    MinValue = if ($minVal -eq [int]::MaxValue) { 'n/a' } else { $minVal }
    MaxValue = if ($maxVal -eq [int]::MinValue) { 'n/a' } else { $maxVal }
  }
}

function Inspect-Pic {
  param([string]$Path)
  $bytes = [System.IO.File]::ReadAllBytes($Path)
  # BSAVE header: 0xFD + 2-byte segment + 2-byte offset + 2-byte length + data + 0x1A trailer
  $magic = '0x{0:X2}' -f $bytes[0]
  $segment = ([int]$bytes[1]) -bor (([int]$bytes[2]) -shl 8)
  $offset = ([int]$bytes[3]) -bor (([int]$bytes[4]) -shl 8)
  $length = ([int]$bytes[5]) -bor (([int]$bytes[6]) -shl 8)
  [PSCustomObject]@{
    Name = (Split-Path $Path -Leaf)
    Bytes = $bytes.Length
    Magic = $magic
    Segment = ('0x{0:X4}' -f $segment)
    Offset = ('0x{0:X4}' -f $offset)
    PayloadLength = $length
    Trailer = ('0x{0:X2}' -f $bytes[$bytes.Length - 1])
  }
}

$pacFiles = Get-ChildItem $OrgPath -Filter '*.PAC' -File
$pctFiles = Get-ChildItem $OrgPath -Filter '*.PCT' -File
$picFiles = Get-ChildItem $OrgPath -Filter '*.PIC' -File

$pacResults = foreach ($f in $pacFiles) { Inspect-Pac -Path $f.FullName }
$pctResults = foreach ($f in $pctFiles) { Inspect-Pct -Path $f.FullName }
$picResults = foreach ($f in $picFiles) { Inspect-Pic -Path $f.FullName }

# Console output
"== .PAC files ($($pacFiles.Count)) =="
$pacResults | Format-Table -AutoSize
"== .PCT files ($($pctFiles.Count)) =="
$pctResults | Format-Table -AutoSize
"== .PIC files ($($picFiles.Count)) =="
$picResults | Format-Table -AutoSize | Out-String -Width 200

# Markdown report
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# DV1 Resource File Inventory')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by tools/inspect_resources.ps1. Documents the format of each resource file type in org/.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Format summary')
[void]$sb.AppendLine()
[void]$sb.AppendLine('### .PIC files - uniform format')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Binary BSAVE files. All are 16391 bytes = 7-byte header + 16384-byte payload. Header decodes to segment 0xB800, offset 0x0000, length 0x4000. These are direct dumps of the CGA SCREEN 1 video page, loaded with `DEF SEG = &HB800: BLOAD "<name>.pic", 0`.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('### .PAC files - multiple sub-formats')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Text CSV but the structure varies by purpose:')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Sub-format | Files | Structure |')
[void]$sb.AppendLine('|-----------|-------|-----------|')
[void]$sb.AppendLine('| **Hit map** | ROOM1-11, DESK, OPENCLOS, RACK, SAFE, TABLE, WINDOW | `palette4tuple` header + `x,y,objID` rows + `0,0,0` padding to 100 entries. Clickable region map per scene. |')
[void]$sb.AppendLine('| **Blank hit map** | DEATH, DINDEAD, LIGHTN | Same header, all entries are `0,0,0`. Non-interactive cutscenes. |')
[void]$sb.AppendLine('| **Object descriptions** | OBJECT.PAC | `objID,"description"` pairs. 25+ inventory item LOOK descriptions. Equivalent to Dream-Giver `des$()`. |')
[void]$sb.AppendLine('| **Save game** | SAVERA-E.PAC | `"name",score,time,"","cursor1","cursor2","slot"` + flag list. Loaded by save/restore code. |')
[void]$sb.AppendLine('| **Embedded BASIC source** | ENDER.PAC | Literal QB4.5 source (`DEFINT`, `SCREEN`, `PALETTE`, `BLOAD`, `PLAY`, `SOUND`). The ending sequence, likely CHAINed or RUN at game end. |')
[void]$sb.AppendLine()
[void]$sb.AppendLine('### .PCT files - sprite data')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Text CSV of integers from QB GET arrays. Width varies by sprite:')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| File | Width | Subject |')
[void]$sb.AppendLine('|------|-------|---------|')
[void]$sb.AppendLine('| DOOR.PCT | 4 ints/row | Cursor or door sprite (large) |')
[void]$sb.AppendLine('| GOLF.PCT, JOED, JOES, JOEW1-4, WILB | 2 ints/row | Character sprites (Joe walking 1-4, dying, standing; Wilbur; golf club) |')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## .PAC files (' + $pacFiles.Count + ')')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Name | Bytes | Header | Entries | Zero padding | Valid |')
[void]$sb.AppendLine('|------|-------|--------|---------|--------------|-------|')
foreach ($r in $pacResults) {
  [void]$sb.AppendLine("| $($r.Name) | $($r.Bytes) | ``$($r.Header)`` | $($r.Entries) | $($r.ZeroPadding) | $($r.LinesValid) |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## .PCT files (' + $pctFiles.Count + ')')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Name | Bytes | Rows | Malformed | Min value | Max value |')
[void]$sb.AppendLine('|------|-------|------|-----------|-----------|-----------|')
foreach ($r in $pctResults) {
  [void]$sb.AppendLine("| $($r.Name) | $($r.Bytes) | $($r.Rows) | $($r.Malformed) | $($r.MinValue) | $($r.MaxValue) |")
}
[void]$sb.AppendLine()
[void]$sb.AppendLine('## .PIC files (' + $picFiles.Count + ')')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Name | Bytes | Magic | Segment | Offset | Payload | Trailer |')
[void]$sb.AppendLine('|------|-------|-------|---------|--------|---------|---------|')
foreach ($r in $picResults) {
  [void]$sb.AppendLine("| $($r.Name) | $($r.Bytes) | $($r.Magic) | $($r.Segment) | $($r.Offset) | $($r.PayloadLength) | $($r.Trailer) |")
}

[System.IO.File]::WriteAllText($OutPath, $sb.ToString())
"Wrote $OutPath"
