# Scans GAME.BAS for numeric literals that match variable addresses from the
# symbol table. Spring's decompiler sometimes substituted a variable's
# data-segment address as a literal value (the 12104 = I375 bug pattern).
#
# Outputs a report grouped by likely context (PALETTE/SOUND/PLAY/assignment).
param(
  [string]$DecompPath = "C:\Code\darkv-bas\Decompile\GAME6.TXT",
  [string]$BasPath = "C:\Code\darkv-bas\Decompile\Recon\GAME.BAS",
  [string]$OutPath = "C:\Code\darkv-bas\Decompile\Recon\SPRING_ADDR_BUGS.md"
)

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$syms = & "$here\parse_symbol_table.ps1" -Path $DecompPath

# Build map: decimal address -> variable name(s)
$addrMap = @{}
foreach ($s in $syms) {
  if ($addrMap.ContainsKey($s.Address)) {
    $addrMap[$s.Address] = $addrMap[$s.Address] + "," + $s.Name
  } else {
    $addrMap[$s.Address] = $s.Name
  }
}

$lines = Get-Content $BasPath
$findings = New-Object System.Collections.Generic.List[PSCustomObject]

for ($n = 0; $n -lt $lines.Count; $n++) {
  $line = $lines[$n]

  # Skip comment-only lines and symbol-table tail
  if ($line -match "^'") { continue }
  if ($line -match "^Rem ") { continue }

  # Find numeric literals. Exclude:
  #   - the leading QB line number
  #   - numbers in obvious string literals "..."
  #   - small numbers (< 100) that are likely real constants
  # Strip the leading line number if present:
  $body = $line
  if ($body -match '^\s*\d+\s+(.+)$') { $body = $Matches[1] }

  # Strip everything inside double quotes (PRINT strings, PLAY notation, etc.)
  $stripped = [regex]::Replace($body, '"[^"]*"', '""')

  # Find numeric literals 100+ (smaller numbers are too common as real constants)
  foreach ($m in ([regex]::Matches($stripped, '\b(\d{3,5})\b'))) {
    $val = [int]$m.Groups[1].Value
    if ($val -lt 100) { continue }
    if ($val -gt 16400) { continue } # data segment ends ~0x4054
    if (-not $addrMap.ContainsKey($val)) { continue }

    # Determine context heuristically
    $context = "?"
    if ($line -match '\bPalette\s+\d+\s*,\s*' + $val + '\b') { $context = "PALETTE arg2 (color value)" }
    elseif ($line -match '\bColor\s+' + $val + '\b') { $context = "COLOR arg" }
    elseif ($line -match '\bSOUND\s+' + $val + '\b') { $context = "SOUND freq" }
    elseif ($line -match '=\s*' + $val + '\s*$') { $context = "assignment value" }
    elseif ($line -match '=\s*' + $val + '#?\b') { $context = "assignment value (with comparison)" }
    elseif ($line -match '\bGoTo\s+' + $val + '\b') { $context = "GoTo target - likely real line number" }
    elseif ($line -match '\bGOSUB\s+' + $val + '\b') { $context = "GOSUB target - likely real line number" }
    elseif ($line -match 'Then\s+GoTo\s+' + $val + '\b') { $context = "If/Then GoTo target" }
    elseif ($line -match '<>\s*' + $val + '\b' -or $line -match '<=\s*' + $val + '\b' -or $line -match '>=\s*' + $val + '\b') { $context = "comparison constant" }

    $findings.Add([PSCustomObject]@{
      LineNumber = $n + 1
      Value = $val
      ValueHex = ('0x{0:X4}' -f $val)
      Variable = $addrMap[$val]
      Context = $context
      Line = $line.Trim()
    }) | Out-Null
  }
}

# Filter: GOTO/GOSUB targets are almost always REAL line numbers, not bugs.
# Also filter out PASS2-RECON DIM block lines (mine), FOR-loop bounds (typically real),
# coordinate-pair PUT/GET args, and assignment-with-comparison contexts.
# True Spring address bugs are in function-call args where the value is 4-5 digits.
$suspicious = $findings | Where-Object {
  $_.Context -notmatch 'GoTo target|GOSUB target|If/Then GoTo' -and
  $_.Line -notmatch '^DIM\s' -and
  $_.Line -notmatch '\bFor\s+\w+\s*=' -and
  $_.Line -notmatch '^L\d+\s*=\s*\d+\s*''PASS2' -and
  $_.Value -ge 1000
}
$jumpTargets = $findings | Where-Object { $_.Context -match 'GoTo target|GOSUB target|If/Then GoTo' }

# Build report
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Spring Address-as-Literal Bug Scan')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Generated by tools/scan_address_literals.ps1.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Spring sometimes substituted a variable''s data-segment address as a literal value.')
[void]$sb.AppendLine('Example confirmed: `Palette 1, 12104` should have been `Palette 1, I375` (I375''s address is 0x2F48 = 12104).')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Summary')
[void]$sb.AppendLine()
[void]$sb.AppendLine("- Total matches found: **$($findings.Count)**")
[void]$sb.AppendLine("- Suspicious (non-jump context): **$($suspicious.Count)**")
[void]$sb.AppendLine("- Likely-real jump targets: **$($jumpTargets.Count)**")
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Suspicious matches (likely Spring address substitution bugs)')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| File line | Value | Var | Context | Code |')
[void]$sb.AppendLine('|-----------|-------|-----|---------|------|')
foreach ($f in ($suspicious | Sort-Object LineNumber)) {
  $code = $f.Line -replace '\|', '\|'
  [void]$sb.AppendLine("| $($f.LineNumber) | $($f.Value) | $($f.Variable) | $($f.Context) | ``$code`` |")
}

[System.IO.File]::WriteAllText($OutPath, $sb.ToString())
"Wrote $OutPath"
"  Total matches: $($findings.Count)"
"  Suspicious (likely bugs): $($suspicious.Count)"
"  Jump targets (likely real): $($jumpTargets.Count)"
